import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import React, { ReactNode } from "react";
import Navbar from "./components/navbar";

const RootLayout = ({ children }: { children:ReactNode }) => {
  return (
    <html>
      <body>
        <Navbar />
        <div className="py-32"> {children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
