import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import React, { ReactNode } from "react";
import Navbar from "./components/navbar/navbar";
import Model from "./components/Models/Model";
import LoginModel from "./components/Models/LoginModel";
import SignupModel from "./components/Models/SignupModel";
import AddPropertyModel from "./components/Models/AddPropertyModel";

const RootLayout = ({ children }: { children: ReactNode }) => {
  const content = <p>hi hello</p>;

  return (
    <html>
      <body>
        <Navbar />
        <div className="py-32"> {children}</div>
        <LoginModel />
        <SignupModel/>
        <AddPropertyModel/>
      </body>
    </html>
  );
};

export default RootLayout;
